name: 'Readme Generator'
on:
  push:
    branches:
     - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  readme:
    name: "Readme generator"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate README
        run: node generate.js
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_BOT }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: shyim
          commit_user_email: github@shyim.de
          commit_author: Shyim <github@shyim.de>
